academicScheduling/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('classTeacher/', include('classTeacher.urls')),
    path('admin/', admin.site.urls),
]

classTeacher/templates/classTeacher/urls.py
"""Module url configuration for the classTeacher app"""
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('chart/', views.chart, name='chart'),
]

classTeacher/urls.py
"""Module url configuration for the classTeacher app"""
from django.urls import path
from . import views

app_name = 'classTeacher'
urlpatterns = [
    path('', views.index, name='index'),
    path('json/WSmxe/', views.wsMateriasEstudiante, name='materias_estudiante'),
    path('json/WShxm/', views.wsHistorialMaterias, name='historial_materias'),
    path('json/WSinfod', views.wsInfoDocentes, name='info_docentes'),
    path('chartComponentes/', views.chartComp, name='chartComp'),
    path('chartProfesores/', views.chart, name='chart'),
    path('profesor_list/', views.profesor_list, name='profe_list'),
    path('profesor/create/', views.profe_create, name='profe_create'),
    path('profesor/<int:pk>/update/', views.profe_update, name='profe_update'),
    path('profesor/<int:pk>/delete/', views.profe_delete, name='profe_delete'),
    path('materia_list/', views.materia_list, name='materia_list'),
    path('materia/create/', views.materia_create, name='materia_create'),
    path('materia/<str:pk>/update/', views.materia_update, name='materia_update'),
    path('materia/<str:pk>/delete/', views.materia_delete, name='materia_delete'),
    path('proyeccion_table/', views.proyeccion_table, name='proyeccion'),
    path('dicts/', views.student, name='dictionary'),
    path('export/xls/', views.export_proyeccion_xls, name='export_proyeccion_xls'),
]

classTeacher/forms.py
from django import forms
from .models import Profesor, Materia

class ProfesorForm(forms.ModelForm):
    class Meta:
        model = Profesor
        fields = (
            'codigo', 'nombre', 'apellido', 'correo', 'carga',
            'restricciones_horario'
        )


class materiaForm(forms.ModelForm):
    class Meta:
        model = Materia
        fields = (
            'codigo', 'nombre', 'creditos', 'semestre', 'prioridad',
            'cupo', 'departamento', 'programa', 'horas_semanales',
            'horas_presenciales', 'semanas', 'componente','area'
        )

classTeacher/templates/classTeacher/views.py
"""module views for the app classTeacher"""
from django.shortcuts import render
from .pygalChart import testChart

# Create your views here.


def index(request):
    """index classTeacher app"""
    # procesar_info()
    # linea q inicia el flujo del programa cuando se hace peticion al index
    return render(request, 'classTeacher/index.html', {})


def chart(request):
    """Chart view"""
    return render(request, 'classTeacher/chart.html', {'chart': testChart()})

classTeacher/views.py
"""module views for the app classTeacher"""
import os
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.forms import ModelForm
from django.views.decorators.csrf import csrf_exempt
from .utilidades import *
from .proyeccion import *
from .confInicial import *
from .graficos import profesoresChart, componentesChart
from .models import Profesor, Materia, Proyeccion
from django_tables2 import RequestConfig
from .tables import ProyeccionTable
import xlwt
from django.http import HttpResponse
from .forms import ProfesorForm, materiaForm

# Create your views here.


def index(request):

    # peticionDatosWS()
    #iniciarProyeccion([], [])
    iniciarConf()
    return render(request, 'classTeacher/index.html', {})


@csrf_exempt
def wsMateriasEstudiante(request):

    pwd = os.path.dirname(__file__)
    archivo = open(pwd +
                   '/static/classTeacher/JSONData/materiasDisponibles.json')
    # 2 archivos json con la mism info diferente estructura

    data1 = json.load(archivo)
    dataJSON = json.dumps(data1)
    archivo.close()
    # print(dataJSON)
    # data = {"materiasEst": dataJSON}

    return JsonResponse(dataJSON, safe=False)


def wsHistorialMaterias(request):
    pwd = os.path.dirname(__file__)
    archivo = open(pwd + '/static/classTeacher/JSONData/Historico.json')

    data1 = json.load(archivo)
    dataJSON = json.dumps(data1)
    archivo.close()
    # print(dataJSON)
    data = {"historicoMateria": dataJSON}
    return JsonResponse(dataJSON, safe=False)


def wsInfoDocentes(request):
    pwd = os.path.dirname(__file__)
    archivo = open(pwd + '/static/classTeacher/JSONData/Profesores.json')

    data1 = json.load(archivo)
    dataJSON = json.dumps(data1)
    archivo.close()
    # print(dataJSON)
    data = {"infoDoc": dataJSON}
    return JsonResponse(dataJSON, safe=False)


def chart(request):
    """Chart view"""
    return render(request, 'classTeacher/chartProfesores.html',
                  {'chart': profesoresChart()})


def chartComp(request):
    """Chart view"""
    return render(request, 'classTeacher/chartComponentes.html',
                  {'chartComp': componentesChart()})


def proyeccion_table(request):
    proyeccion = ProyeccionTable(Proyeccion.objects.all())
    RequestConfig(request).configure(proyeccion)
    return render(request, 'classTeacher/proyeccion_table.html', {'proyeccion': proyeccion})


def export_proyeccion_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="proyeccion.xls"'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Proyeccion')
    # Sheet header, first row
    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    columns = ['Materia', 'Cantidad grupos', 'Cantidad Estudiantes', 'Promedio Historico','Periodo' ]

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    rows = Proyeccion.objects.all().values_list('materia', 'cantidad_grupos', 'cantidad_estudiantes', 'promedio_historico','periodo')
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)
    return response

# ------------------Empieza la parte de CRUD profesores

def profesor_list(request, template_name='classTeacher/profesor_list.html'):
    profe = Profesor.objects.all()
    data = {}
    data['profesores'] = profe
    return render(request, template_name, data)

def guardar_formulario(request, form, template):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            profesores = Profesor.objects.all()
            data['html_profesor_list'] = render_to_string('classTeacher/profe_parcial_list.html', {
                'profesores': profesores
            })
        else:
            data['form_is_valid'] = False    
    context = {'form': form}
    data['html_form'] = render_to_string(template, context, request=request)
    return JsonResponse(data)

def profe_create(request):
    if request.method == 'POST':
        form = ProfesorForm(request.POST)
    else:
        form = ProfesorForm()
    return guardar_formulario(request, form, 'classTeacher/profe_parcial_create.html')


def profe_update(request, pk):
    profesor = get_object_or_404(Profesor, pk=pk)
    if request.method == 'POST':
        form = ProfesorForm(request.POST, instance=profesor)
    else:
        form = ProfesorForm(instance=profesor)
    return guardar_formulario(request, form, 'classTeacher/profe_parcial_update.html')


def profe_delete(request, pk):
    profesor = get_object_or_404(Profesor, pk=pk)
    data = dict()
    if request.method == 'POST':
        profesor.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        profesores = Profesor.objects.all()
        data['html_profesor_list'] = render_to_string('classTeacher/profe_parcial_list.html', {
            'profesores': profesores
        })
    else:
        context = {'profesor': profesor}
        data['html_form'] = render_to_string('classTeacher/profe_parcial_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)

# ------------------Empieza la parte de CRUD Materias
def materia_list(request, template_name='classTeacher/materia_list.html'):
    mate = Materia.objects.all()
    data = {}
    data['materias'] = mate
    return render(request, template_name, data)

def guardar_formulario_materias(request, form, template):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            materias = Materia.objects.all()
            data['html_materia_list'] = render_to_string('classTeacher/materia_parcial_list.html', {
                'materias': materias
            })
        else:
            data['form_is_valid'] = False    
    context = {'form': form}
    data['html_form'] = render_to_string(template, context, request=request)
    return JsonResponse(data)

def materia_create(request):
    if request.method == 'POST':
        form = materiaForm(request.POST)
    else:
        form = materiaForm()
    return guardar_formulario_materias(request, form, 'classTeacher/materia_parcial_create.html')


def materia_update(request, pk):
    materia = get_object_or_404(Materia, pk=pk)
    if request.method == 'POST':
        form = materiaForm(request.POST, instance=materia)
    else:
        form = materiaForm(instance=materia)
    return guardar_formulario_materias(request, form, 'classTeacher/materia_parcial_update.html')


def materia_delete(request, pk):
    materia = get_object_or_404(Materia, pk=pk)
    data = dict()
    if request.method == 'POST':
        materia.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        materias = Materia.objects.all()
        data['html_materia_list'] = render_to_string('classTeacher/materia_parcial_list.html', {
            'materias': materias
        })
    else:
        context = {'materia': materia}
        data['html_form'] = render_to_string('classTeacher/materia_parcial_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)



#----------------prueba web service------------
def student(request, template_name='classTeacher/dicts.html'):
    dicts = peticionsita(1701315087)
    return render(request, template_name, {'dictionary': dicts})

classTeacher/templates/classTeacher/base_generic.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- Bootstrap CSS -->
  {% block title %}<title>Horario Semestral</title>{% endblock %}
  <link rel="stylesheet" href="{% static 'classTeacher/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'classTeacher/images/open-iconic/font/css/open-iconic.css' %}">
  <link rel="stylesheet" href="{% static 'classTeacher/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'classTeacher/images/open-iconic/font/css/open-iconic-bootstrap.min.css' %}">
  <!--- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
  <!-- open-iconic-bootstrap (icon set for bootstrap) -->
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />-->
</head>
<body>

    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
         <div class="sidebar-header">
            <h3><a target="_self" href="{% url 'classTeacher:index'%}">
              <img src= "{% static 'classTeacher/images/facultadBlanco.png' %}"/></h3>
            <strong>AS</strong>
         </div>
            <ul class="list-unstyled components">
             <p style="text-align: center">Escoge</p>
             <li class="active">
                 <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">
                 Proyección
                 <span class="oi oi-caret-bottom " style="margin-left: 50%"></span>
               </a>
                 <ul class="collapse list-unstyled" id="homeSubmenu">
                     <li class="active"><a href="{% url 'classTeacher:chart'%}">Reporte 1</a></li>
                     <li class="active"><a href="{% url 'classTeacher:chartComp'%}">Reporte 2</a></li>
                     <li class="active"><a href="{% url 'classTeacher:proyeccion'%}">Reporte 3</a></li>
                 </ul>
             </li>
             <li class="active">
                 <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">Gestión<span class="oi oi-caret-bottom" style="margin-left: 63%"></span></a>
                 <ul class="collapse list-unstyled" id="pageSubmenu">
                     <li class="active"><a href="{% url 'classTeacher:profe_list'%}">Profesores</a></li>
                     <li class="active"><a href="{% url 'classTeacher:materia_list'%}">Clases</a></li>
                 </ul>
             </li>
             <li class="active"><a href="#">Calendario</a></li>
             <li class="active"><a href="#">Calculo de horarios</a></li>
         </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <span class="oi oi-menu"></span>
                    </button>
            </nav>

            {% block content %}
            <h2>Collapsible Sidebar Using Bootstrap 4</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <div class="line"></div>

            <h2>Lorem Ipsum Dolor</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <div class="line"></div>

            <h2>Lorem Ipsum Dolor</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <div class="line"></div>

            <h3>Lorem Ipsum Dolor</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            {% endblock %}
        </div>
    </div>
      <!-- Aquí van todos los JavaScript -->
  <!-- jQuery primero, luego Popper.js, luego Bootstrap JS -->
<script type="text/javascript" src="{% static 'classTeacher/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'classTeacher/js/popper.js' %}"></script>
<script type="text/javascript" src="{% static 'classTeacher/js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'classTeacher/js/main.js' %}"></script>
{% block scripts %}
{% endblock %}
</body>

</html>

classTeacher/templates/classTeacher/chartComponentes.html
{% extends "classTeacher/base_generic.html" %}
{% block title %}<title>Diagrama</title>{% endblock %}
    {% block content %}
    <div class="container">
        <embed type="image/svg+xml" src= {{ chartComp|safe }} />
    </div>
    {% endblock %}

classTeacher/templates/classTeacher/chartProfesores.html
{% extends "classTeacher/base_generic.html" %}
{% block title %}<title>Diagrama</title>{% endblock %}
    {% block content %}
    <div class="container-fluid">
        <embed type="image/svg+xml" src= {{ chart|safe }} />
    </div>
    {% endblock %}

classTeacher/templates/classTeacher/dicts.html
{% extends "classTeacher/base_generic.html" %}
{% block title %}<title>Diagrama</title>{% endblock %}
    {% block content %}
    <ul>
    {% for codigo, value in dictionary.items %}
      <li>{{codigo}}: {{value}}</li>
    {% endfor %}
  {% endblock %}

classTeacher/templates/classTeacher/index.html
{% extends "classTeacher/base_generic.html" %}
{% block content %}
<div class="line"></div>
<h2>Bienvenido a Academic Scheduling!</h2>
<p>La planificación académica de las universidades involucra compensar virtualmente varios factores en términos académicos, financieros y logísticos.
  Al inicio de cada semestre, las facultades, jefes de carreras y administradores de las instituciones
  de educación superior deben enfrentarse a la frustración de muchos estudiantes y profesores.
  Esta herramienta se crea con el fin de acabar con esa frustración.
</p>
<div class="line"></div>
<div class="cargando text-center">
    <button class="btn btn-primary" id="cargar" data-toggle="modal" data-target="#exampleModal">Iniciar Proyección</button>
</div>
  <div class="modal" id="exampleModal">
  <div class="modal-body">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close" >
      <span aria-hidden="true" class="oi oi-circle-x" style="color: white"></span>
    </button>
        <div class="container">
  <div class="cube">
    <div class="sides">
      <div class="top"></div>
      <div class="right"></div>
      <div class="bottom"></div>
      <div class="left"></div>
      <div class="front"></div>
      <div class="back"></div>
    </div>
  </div>
  <div class="text">Cargando la proyección</div>
</div>
  </div>
  </div>
{% endblock %}

classTeacher/templates/classTeacher/materia_list.html
{% extends "classTeacher/base_generic.html" %}
{% load static %}
{% block content %}
<h1>Materias</h1>
 <p>
    <button type="button" class="btn btn-primary js-crear-materia" data-url="{% url 'classTeacher:materia_create' %}">
      <span class="oi oi-book"></span>
      Añadir Materia
    </button>
  </p>
<table  class="table" id="tabla-materias">
  <thead>
    <tr>
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Componente</th>    
    <th>Acciones</th>
    </tr>
</thead>
<tbody>
    {% include 'classTeacher/materia_parcial_list.html' %}
</tbody>
</table>
 <!-- THE MODAL WE WILL BE USING -->
  <div class="modal fade" id="modal-materia">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
{% endblock%}
{% block scripts %}
  <script src="{% static 'classTeacher/js/materias.js' %}"></script>
{% endblock %}

classTeacher/templates/classTeacher/materia_parcial_create.html
<form method="post" action="{% url 'classTeacher:materia_create' %}" class="js-materia-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close" >
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Añadir una materia</h4>
  </div>
  <div class="modal-body">
        {% include 'classTeacher/materia_parcial_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
    <button type="submit" class="btn btn-primary">Añadir</button>
  </div>
</form>

classTeacher/templates/classTeacher/materia_parcial_list.html
{% for materia in materias %}
    <tr>
        <td>{{ materia.codigo }}</td>
        <td>{{ materia.nombre }}</td>
        <td>{{ materia.componente }}</td>
        <td>
            <button type="button" class="btn btn-warning btn-sm js-update-materia" data-url="{% url 'classTeacher:materia_update' materia.codigo %}"> <span class="oi oi-pencil"></span></button>
              <button type="button" class="btn btn-danger btn-sm js-delete-materia" data-url="{% url 'classTeacher:materia_delete' materia.codigo %}"><span class="oi oi-trash"></span> </button>
        </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="7" class="text-center bg-warning">No existen materias</td>
    </tr>
    {% endfor %}

classTeacher/templates/classTeacher/materia_parcial_update.html
<form method="post" action="{% url 'classTeacher:materia_update' form.instance.codigo %}" class="js-materia-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Modificar Materia</h4>
  </div>
  <div class="modal-body">
    {% include 'classTeacher/materia_parcial_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
    <button type="submit" class="btn btn-primary">Guardar</button>
  </div>
</form>

classTeacher/templates/classTeacher/profe_parcial_create.html
<form method="post" action="{% url 'classTeacher:profe_create' %}" class="js-profe-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close" >
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Añadir un profesor</h4>
  </div>
  <div class="modal-body">
        {% include 'classTeacher/profe_parcial_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
    <button type="submit" class="btn btn-primary">Añadir</button>
  </div>
</form>

classTeacher/templates/classTeacher/profe_parcial_delete.html
<form method="post" action="{% url 'classTeacher:profe_delete' profesor.codigo %}" class="js-profe-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirmar Eliminación</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Esta seguro que quiere eliminar a <strong>{{ profesor.nombre }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
    <button type="submit" class="btn btn-danger">Eliminar profesor</button>
  </div>
</form>

classTeacher/templates/classTeacher/profe_parcial_update.html
<form method="post" action="{% url 'classTeacher:profe_update' form.instance.codigo %}" class="js-profe-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Modificar Profesor</h4>
  </div>
  <div class="modal-body">
    {% include 'classTeacher/profe_parcial_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
    <button type="submit" class="btn btn-primary">Guardar</button>
  </div>
</form>

classTeacher/templates/classTeacher/profesor_list.html
{% extends "classTeacher/base_generic.html" %}
{% load static %}
{% block content %}
<h1>Profesores</h1>
 <p>
    <button type="button" class="btn btn-primary js-crear-profesor" data-url="{% url 'classTeacher:profe_create' %}">
      <span class="oi oi-person"></span>
      Añadir profesor
    </button>
  </p>
<table  class="table" id="tabla-profesores">
  <thead>
    <tr>
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Acciones</th>
    </tr>
</thead>
<tbody>
    {% include 'classTeacher/profe_parcial_list.html' %}
</tbody>
</table>
 <!-- THE MODAL WE WILL BE USING -->
  <div class="modal fade" id="modal-profesor">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
{% endblock%}
{% block scripts %}
  <script src="{% static 'classTeacher/js/profesor.js' %}"></script>
{% endblock %}

classTeacher/templates/classTeacher/proyeccion_table.html
{% extends "classTeacher/base_generic.html" %}
{% block content %}
<h1>Proyeccion</h1>
<a href="{% url 'classTeacher:export_proyeccion_xls' %}">Exportar la proyección</a>
{% load render_table from django_tables2 %}
    {% render_table proyeccion %}
{% endblock%}